management:
  # Disabling HTTP Endpoints
  server:
    port: -1
  endpoints:
    access:
      # 端点本身不创建
      default: none
    web:
      exposure:
        # 已创建的端点也不通过 HTTP 暴露
        exclude: "*"
      discovery:
        # 关闭 /actuator 发现页本身
        enabled: false
